AMAZON_ACCESS_KEY = "YOUR_ACCESS_KEY"
AMAZON_SECRET_KEY = "YOUR_SECRET_KEY"
AMAZON_ASSOCIATE_TAG = "carlindsouza-21"
AMAZON_REGION = "IN"  # change to US/UK/CA etc.

DISCORD_BOT_TOKEN = "YOUR_DISCORD_BOT_TOKEN"
